### ISSUE TITLE
Migrate to org-roam v2

### ISSUE THREAD

**Issue by bphenriques** [bphenriques/knowledge-base#6]
To keep up-to-speed, it would be great supporting org-roam v2 which requires an `ID` as property.

However, the following tickets `ox-hugo` need to be addressed:
- https://github.com/kaushalmodi/ox-hugo/issues/447 - No workaround that I know 🤔 
- https://github.com/kaushalmodi/ox-hugo/issues/443 - Duplicate `#+ROAM_TAGS`  and `#+FILETAGS`.

Relates to https://github.com/bphenriques/dotfiles/pull/8

**Comment by kaushalmodi** [comment]
Hello!

Were those blocking issues resolved for you? If so, can you reply in those ox-hugo with your solution. That might help other Org Roam users?

Thanks!

**Comment by bphenriques** [comment]
Hello!

Ofc. I will post on the tickets :)
