### ISSUE TITLE
invalid nested repetition operator: `++`

### ISSUE THREAD

**Issue by FelixBrendel** [bphenriques/knowledge-base#7]
I wasn't sure if this issue belongs here or in the explorer theme repository.

I tried to use this repository as a base for my own roam notes. The first problem I encoutered, was that git did not allow me to fetch the submodule over ssh (on windows). I could fix it by changing the remote url for the submodule to use https.

The main problem I am facing is that hugo would not build the site. Hugo complains:

```
Start building sites …
hugo v0.92.2-CDF6A0D6+extended windows/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:38:11: executing "_default/single.html" at <partial "menu-right-content" .>: error calling partial: execute of template failed: template: partials/menu-right-content.html:17:3: executing "partials/menu-right-content.html" at <partial "component/backlinks" .>: error calling partial: execute of template failed: template: partials/component/backlinks.html:4:11: executing "partials/component/backlinks.html" at <partial "util/is-backlink" (dict "First" $.Page "Second" $other)>: error calling partial: execute of template failed: template: partials/util/is-backlink.html:16:5: executing "partials/util/is-backlink.html" at <findRE (printf "['\"\\s]?%s['\"\\s]" (lower .First.Title)) (lower .Second.RawContent)>: error calling findRE: error parsing regexp: invalid nested repetition operator: `++`
Built in 791 ms
```
I could not use your batch export script, since my roam files lie in directory hiearchy so I already have my own export script, but looking at yours I was not able to find a reason why the export process should be the issue.

If I just put a few files in the content directory the site works well, however with all files in there, I see the error. It is hard to find which file exactly causes the error since incrementally adding files generally does not work since they all link to each other and missing references also produce errors.

Do you have any idea how this error could come up?

**Comment by FelixBrendel** [comment]
Uppon looking at the code more and not understanding how there was a nested regex repitition operator ++, I realized I have a note with the title `PointNet++` (a famous computer vision paper). When the title is inserted there with the `%s` it would result in a  `++`. Maybe is there a way to escape the title such that the title is not interpreted as a regular expression?

**Comment by bphenriques** [comment]
Hello! 👋 

Yeah, it should be in the other repository (which is essentially in maintainance mode). No problem. Can you share with me your setup so that I can try to reproduce?

**Comment by FelixBrendel** [comment]
Sure!
A simple way to reproduce it:

```
git clone https://github.com/bphenriques/knowledge-base 
cd knowledge-base/themes
git clone https://github.com/bphenriques/explorer-hugo-theme/ explorer
cd ..
mkdir content
mkdir content/notes
```

Then put a hugo markdown file into the `notes` folder which has `++` as part of the title, for example:

```md
+++
title = "PointNet++"
author = ["Felix Brendel"]
lastmod = 2022-02-16T20:46:45+01:00
tags = ["deep-learning", "ML-4-3d", "paper"]
draft = false
+++

Similar goals as PointNet but tries to capture the local structures of the
points by using hierarchical processing.
```

When trying to do `hugo serve` the error will occur.

I agree, this is more of a issue with the theme.

**Comment by bphenriques** [comment]
👋  Thank you! 

I managed to reproduce your file and fix. It was as you said. For now, backlink searching is excluding characters such as `+(){}|\?$^`, let me know if it is working for you!

Preview of your file:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/4727729/154540884-1cc3be7d-244e-4e82-909b-e40198ebe93b.png">

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4727729/154540905-77cb0287-58a2-4dbb-9d80-4978f5cbd25c.png">

PS: I also changed the way the title is rendered so that the `++` are displayed. The release is `v0.2.0`.

Thank you for reaching out!

**Comment by FelixBrendel** [comment]
Thank you that's great! I'll have a look soon!

**Comment by FelixBrendel** [comment]
I tested it at it seems to work brilliantly! Thank you again
